import { offscreen } from './canvas';

/**
 * Text-grid pixel art.
 *
 * Sprites are authored as rows of characters plus a palette mapping each
 * character to a color (or null for transparent):
 *
 *   sprite(["..PP..",
 *           ".PWWP.",
 *           "..PP.."], { '.': null, P: '#b13e53', W: '#f4f4f4' })
 *
 * This keeps art diffable, hand-editable, and trivially generated by the
 * sprite editor tool. Baked to an offscreen canvas once; drawing is a
 * plain drawImage.
 */
export type Palette = Record<string, string | null>;

export interface SpriteData {
  rows: string[];
  palette: Palette;
}

/**
 * EPX / Scale2x upscale of a text grid: each cell becomes 2×2, with
 * corners filled from matching neighbors — the classic pixel-art
 * smoothing that rounds silhouettes without inventing colors. Author at
 * 1×, render at 2× texel density (`sprite(epx(rows), pal)` drawn at
 * half size on a zoomed canvas), or hand-author native 2× art.
 */
export function epx(rows: string[]): string[] {
  const h = rows.length;
  const w = Math.max(...rows.map((r) => r.length));
  const at = (x: number, y: number): string =>
    y < 0 || y >= h || x < 0 || x >= w ? '.' : (rows[y][x] ?? '.');
  const out: string[][] = Array.from({ length: h * 2 }, () => Array(w * 2).fill('.'));
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const P = at(x, y);
      const A = at(x, y - 1); // above
      const B = at(x + 1, y); // right
      const C = at(x - 1, y); // left
      const D = at(x, y + 1); // below
      let p1 = P, p2 = P, p3 = P, p4 = P;
      if (C === A && C !== D && A !== B) p1 = A;
      if (A === B && A !== C && B !== D) p2 = B;
      if (D === C && D !== B && C !== A) p3 = C;
      if (B === D && B !== A && D !== C) p4 = D;
      out[y * 2][x * 2] = p1;
      out[y * 2][x * 2 + 1] = p2;
      out[y * 2 + 1][x * 2] = p3;
      out[y * 2 + 1][x * 2 + 1] = p4;
    }
  }
  return out.map((r) => r.join(''));
}

export function sprite(rows: string[], palette: Palette): HTMLCanvasElement {
  const h = rows.length;
  const w = Math.max(...rows.map((r) => r.length));
  const [c, g] = offscreen(w, h);
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const col = palette[row[x]];
      if (col) {
        g.fillStyle = col;
        g.fillRect(x, y, 1, 1);
      }
    }
  });
  return c;
}

/** Horizontally mirrored copy (for facing left/right without extra art). */
export function flipped(img: HTMLCanvasElement): HTMLCanvasElement {
  const [c, g] = offscreen(img.width, img.height);
  g.translate(img.width, 0);
  g.scale(-1, 1);
  g.drawImage(img, 0, 0);
  return c;
}

const flashCache = new WeakMap<HTMLCanvasElement, HTMLCanvasElement>();

/**
 * Solid-white silhouette of a sprite — the classic hit-flash. Cached per
 * sprite so it's free after first use.
 */
export function whiteOf(img: HTMLCanvasElement): HTMLCanvasElement {
  const hit = flashCache.get(img);
  if (hit) return hit;
  const [c, g] = offscreen(img.width, img.height);
  g.drawImage(img, 0, 0);
  g.globalCompositeOperation = 'source-in';
  g.fillStyle = '#ffffff';
  g.fillRect(0, 0, c.width, c.height);
  flashCache.set(img, c);
  return c;
}

const tintCache = new WeakMap<HTMLCanvasElement, Map<string, HTMLCanvasElement>>();

/** Color-tinted copy of a sprite (palette-swap-lite: recolor variants). */
export function tintOf(img: HTMLCanvasElement, color: string, alpha: number): HTMLCanvasElement {
  const key = `${color}:${alpha}`;
  let m = tintCache.get(img);
  if (m?.has(key)) return m.get(key)!;
  const [c, g] = offscreen(img.width, img.height);
  g.drawImage(img, 0, 0);
  g.globalCompositeOperation = 'source-atop';
  g.globalAlpha = alpha;
  g.fillStyle = color;
  g.fillRect(0, 0, c.width, c.height);
  if (!m) {
    m = new Map();
    tintCache.set(img, m);
  }
  m.set(key, c);
  return c;
}
